"""add_retry_count_to_documents

Revision ID: 56f95856de22
Revises: d8f71c7b730d
Create Date: 2026-08-27 09:25:23.565211

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '56f95856de22'
down_revision: str | Sequence[str] | None = 'd8f71c7b730d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('retry_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'retry_count')
    # ### end Alembic commands ###
